services:
    php:
        container_name: api-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        container_name: api-nginx
        image: "nginx:latest"
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - laravel

    redis:
        container_name: api-redis
        image: redis:alpine
        networks:
            - laravel

    mysql:
        container_name: api-mysql
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: playMarket
            MYSQL_USER: armen
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
